#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  May 10, 2023 10:48:29 PM +03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x500+622+274
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2400 1100
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Serial_Com"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "serial_com_top" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:copy_lock $top
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Параметр 
    vTcl:DefineAlias "$top.lab46" "prmtr_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Значение 1-го канала} 
    vTcl:DefineAlias "$top.lab48" "fr_ch_val_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Значение 2-го канала} 
    vTcl:DefineAlias "$top.lab49" "sec_ch_val_lbl" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe50 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe50" "TSeparator1" vTcl:WidgetProc "serial_com_top" 1
    menu $top.m51 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ttk::separator $top.tSe52
    vTcl:DefineAlias "$top.tSe52" "TSeparator2" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe55 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe55" "TSeparator3" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe56 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe56" "TSeparator4" vTcl:WidgetProc "serial_com_top" 1
    labelframe $top.lab57 \
        \
        -font {-family {MS Reference Sans Serif} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text Подключение \
        -background $vTcl(actual_gui_bg) -height 127 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 267 
    vTcl:DefineAlias "$top.lab57" "connection_frm" vTcl:WidgetProc "serial_com_top" 1
    set site_3_0 $top.lab57
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {COM port:} 
    vTcl:DefineAlias "$site_3_0.lab58" "com_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Baud Rate:} 
    vTcl:DefineAlias "$site_3_0.lab59" "br_lbl" vTcl:WidgetProc "serial_com_top" 1
    ttk::combobox $site_3_0.tCo66 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo66" "Br_box" vTcl:WidgetProc "serial_com_top" 1
    ttk::combobox $site_3_0.tCo67 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo67" "Com_box" vTcl:WidgetProc "serial_com_top" 1
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.224 -width 0 \
        -relwidth 0.267 -height 0 -relheight 0.224 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.672 -width 0 \
        -relwidth 0.267 -height 0 -relheight 0.224 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo66 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.597 -width 0 \
        -relwidth 0.411 -height 0 -relheight 0.224 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo67 \
        -in $site_3_0 -x 0 -relx 0.308 -y 0 -rely 0.149 -width 0 \
        -relwidth 0.411 -height 0 -relheight 0.224 -anchor nw \
        -bordermode ignore 
    button $top.but69 \
        -activebackground #d3ab6d -activeforeground black -background #d3ab6d \
        -compound left -disabledforeground #d3ab6d \
        -font {-family Terminal_Hex -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text {Проверка параметров} 
    vTcl:DefineAlias "$top.but69" "check_params_btn" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent70 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent70" "amp_pos_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent71 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent71" "amp_pos_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent72 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent72" "amp_neg_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent73 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent73" "amp_neg_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent74 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent74" "time_pos_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent75 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent75" "time_neg_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe76
    vTcl:DefineAlias "$top.tSe76" "TSeparator2_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe77
    vTcl:DefineAlias "$top.tSe77" "TSeparator2_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe78
    vTcl:DefineAlias "$top.tSe78" "TSeparator2_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe82
    vTcl:DefineAlias "$top.tSe82" "TSeparator2_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe83
    vTcl:DefineAlias "$top.tSe83" "TSeparator2_1_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe84
    vTcl:DefineAlias "$top.tSe84" "TSeparator2_1_1_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe85
    vTcl:DefineAlias "$top.tSe85" "TSeparator2_1_1_1_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe86
    vTcl:DefineAlias "$top.tSe86" "TSeparator2_1_1_1_1_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    ttk::separator $top.tSe87
    vTcl:DefineAlias "$top.tSe87" "TSeparator2_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent88 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent88" "time_pause_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent89 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent89" "period_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent90 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent90" "numpack_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent91 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent91" "time_frame_entry_ch1" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent93 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent93" "time_pos_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent94 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent94" "time_neg_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent95 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent95" "time_pause_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent96 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent96" "period_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent97 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent97" "numpack_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent98 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent98" "time_frame_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    entry $top.ent99 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent99" "pause_start_entry_ch2" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab101 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {AMP_POS uA} 
    vTcl:DefineAlias "$top.lab101" "amp_pos_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab102 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {AMP_NEG uA} 
    vTcl:DefineAlias "$top.lab102" "amp_neg_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab103 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {TIME_POS us} 
    vTcl:DefineAlias "$top.lab103" "time_pos_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab104 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {TIME_NEG us} 
    vTcl:DefineAlias "$top.lab104" "time_neg_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab105 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {TIME_PAUSE us} 
    vTcl:DefineAlias "$top.lab105" "time_pause_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab106 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {PERIOD us} 
    vTcl:DefineAlias "$top.lab106" "period_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab108 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text NUMPACK 
    vTcl:DefineAlias "$top.lab108" "numpack_lbl" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab109 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {TIME_FRAME us} 
    vTcl:DefineAlias "$top.lab109" "time_frame_lbl" vTcl:WidgetProc "serial_com_top" 1
    button $top.but110 \
        -activebackground #d3ab6d -activeforeground black -background #47fa50 \
        -compound left \
        -font {-family Terminal_Hex -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text {Начало стимуляции} 
    vTcl:DefineAlias "$top.but110" "stimulation_start_btn" vTcl:WidgetProc "serial_com_top" 1
    button $top.but111 \
        -activebackground #d3ab6d -activeforeground black -background #e35e5e \
        -compound left -disabledforeground #d3ab6d \
        -font {-family Terminal_Hex -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff \
        -highlightcolor black -pady 0 -text {Конец стимуляции} 
    vTcl:DefineAlias "$top.but111" "stimulation_stop_btn" vTcl:WidgetProc "serial_com_top" 1
    label $top.lab112 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief solid -text {PAUSE_START us} 
    vTcl:DefineAlias "$top.lab112" "pause_start_lbl" vTcl:WidgetProc "serial_com_top" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr114 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr114" "Scrolledtext1" vTcl:WidgetProc "serial_com_top" 1

    $top.scr114.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.045 -width 0 -relwidth 0.106 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.04 -width 0 -relwidth 0.191 \
        -height 0 -relheight 0.05 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.344 -y 0 -rely 0.045 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.tSe50 \
        -in $top -x 0 -relx 0.143 -y 0 -width 0 -relwidth 0.003 -height 0 \
        -relheight 0.929 -anchor nw -bordermode ignore 
    place $top.tSe52 \
        -in $top -x 0 -y 0 -rely 0.089 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe55 \
        -in $top -x 0 -relx 0.327 -y 0 -width 0 -relwidth 0.003 -height 0 \
        -relheight 0.929 -anchor nw -bordermode ignore 
    place $top.tSe56 \
        -in $top -x 0 -relx 0.55 -y 0 -width 0 -relwidth 0.003 -height 0 \
        -relheight 0.929 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.567 -y 0 -rely 0.067 -width 0 -relwidth 0.417 \
        -height 0 -relheight 0.279 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.413 -width 217 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 0 -relx 0.157 -y 0 -rely 0.104 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent71 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.103 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent72 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.205 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent73 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.205 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent74 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.283 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.386 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe76 \
        -in $top -x 0 -y 0 -rely 0.181 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.002 -anchor nw -bordermode ignore 
    place $top.tSe77 \
        -in $top -x 0 -y 0 -rely 0.27 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe78 \
        -in $top -x 0 -y 0 -rely 0.362 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe82 \
        -in $top -x 0 -y 0 -rely 0.446 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe83 \
        -in $top -x 0 -y 0 -rely 0.54 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe84 \
        -in $top -x 0 -y 0 -rely 0.634 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe85 \
        -in $top -x 0 -y 0 -rely 0.721 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe86 \
        -in $top -x 0 -y 0 -rely 0.824 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.004 -anchor nw -bordermode ignore 
    place $top.tSe87 \
        -in $top -x 0 -y 0 -rely 0.924 -width 0 -relwidth 0.55 -height 0 \
        -relheight 0.008 -anchor nw -bordermode ignore 
    place $top.ent88 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.464 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent89 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.567 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent90 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.645 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent91 \
        -in $top -x 0 -relx 0.157 -y 0 -rely 0.75 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent93 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.283 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent94 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.386 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent95 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.464 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent96 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.567 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent97 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.645 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent98 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.748 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent99 \
        -in $top -x 0 -relx 0.376 -y 0 -rely 0.85 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab101 \
        -in $top -x 0 -y 0 -rely 0.103 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab102 \
        -in $top -x 0 -y 0 -rely 0.205 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab103 \
        -in $top -x 0 -y 0 -rely 0.283 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab104 \
        -in $top -x 0 -y 0 -rely 0.386 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.lab105 \
        -in $top -x 0 -y 0 -rely 0.464 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab106 \
        -in $top -x 0 -y 0 -rely 0.563 -width 0 -relwidth 0.101 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab108 \
        -in $top -x 0 -y 0 -rely 0.646 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.lab109 \
        -in $top -x 0 -y 0 -rely 0.748 -width 0 -relwidth 0.13 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.but110 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.491 -width 217 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but111 \
        -in $top -x 0 -relx 0.609 -y 0 -rely 0.567 -width 217 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab112 \
        -in $top -x 0 -y 0 -rely 0.85 -width 0 -relwidth 0.144 -height 0 \
        -relheight 0.054 -anchor nw -bordermode ignore 
    place $top.scr114 \
        -in $top -x 0 -relx 0.586 -y 0 -rely 0.646 -width 0 -relwidth 0.371 \
        -height 0 -relheight 0.279 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

